### ISSUE TITLE
Controla el indexOutOf....Exception

### ISSUE THREAD

**Issue by lmagarin** [alvaroolt/Examen-Abril#16]
https://github.com/alvaroolt/Examen-Abril/blob/98571b272afbca355cb548f98e88df06e74901bb/src/examenSegundoTrimestreJava/Ejercicio1/negocio/Almacen.java#L152

catch(IOOBException e){
 thow new ArticuloNoExisteException(sfasdfasdf);
}

**Comment by alvaroolt** [comment]
Corregido

**Comment by lmagarin** [comment]
No lo veo corregido...
