### ISSUE TITLE
Quita los catch tan genéricos

### ISSUE THREAD

**Issue by lmagarin** [alvaroolt/Examen-Abril#21]
https://github.com/alvaroolt/Examen-Abril/blob/98571b272afbca355cb548f98e88df06e74901bb/src/examenSegundoTrimestreJava/Ejercicio1/test/TestAlmacen.java#L151
Variable innecesaria. Refactoriza
Puedes utilizar Refactoring.../inline

Revísalo en TODAS las variables

**Comment by alvaroolt** [comment]
Corregido
