### ISSUE TITLE
Paquetes

### ISSUE THREAD

**Issue by lmagarin** [alvaroolt/Examen-Abril#4]
https://github.com/alvaroolt/Examen-Abril/blob/411da0ddf91025f9dbc2885692076de1a0a0b12f/examenSegundoTrimestreJava/Ejercicio1/Almacen.java#L1

- Crea un paquete para la capa de presentación: 
- "ej1.consola.Test.JAVA"
- Crea otro paquete para la capa de negocio: 
- "ej1.negocio.Almacen.java"
- "ej1.negocio.Articulo.java"
- "ej1.negocio.IVA.java"

**Comment by alvaroolt** [comment]
Corregido.
