### ISSUE TITLE
Teclado es un envoltorio de scanner, no de BufferReader

### ISSUE THREAD

**Issue by lmagarin** [alvaroolt/Examen-Abril#6]
https://github.com/alvaroolt/Examen-Abril/blob/11669df6bea1887dafefd051eff80ae28f4e7998/examenSegundoTrimestreJava/utiles/Teclado.java#L58
Lee las especificaciones
https://moodle.iesgrancapitan.org/mod/assign/view.php?id=9684

**Comment by alvaroolt** [comment]
Corregido.
